---

- name: Add authorized_keys for the user
  authorized_key:
    user: "{{ server_user }}"
    state: present
    key: '{{ item }}'
  with_items:
    - "{{ user_public_keys }}"

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

# https://blog.tankywoo.com/linux/2013/09/14/ssh-passwordauthentication-vs-challengeresponseauthentication.html
- name: Disallow password authentication (ChallengeResponseAuthentication)
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^ChallengeResponseAuthentication"
              line="ChallengeResponseAuthentication no"
              state=present
  notify: restart ssh

- name: Disallow PAM (Pluggable Authentication Module) interface
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^UsePAM"
              line="UsePAM no"
              state=present
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart ssh

- name: Allow ssh only for primary user
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^AllowUsers"
              line="AllowUsers {{ server_user }}"
              state=present
  notify: restart ssh
