# NOTE: This route is not recommended for low end vps box, will require larger swap (npm install)
# - name: Install npm
#   apt:
#     update_cache: "{{ update_apt_cache }}"
#     state: present
#     name:
#       - npm
#   tags:
#     - packages
#
# TODO can we get rid of this command, global is bad afterall
# - name: npm install npm@latest -g
#   command: npm install npm@latest -g

# - name: Install node dependencies
#   npm:
#     path: "{{ tmp_build.path }}/src/vue/"
#
# - name: Npm run build
#   command: cd {{ tmp_build.path }}/src/vue/ && npm run build
#
# - name: Move the django content to the project_path
#   command: rsync -r {{ tmp_build.path }}/src/vue/dist/ {{ frontend_web_dir }}/

- name: Build the vuejs files to be deployed (LOCALLY) (Should not require sudo...)
  local_action: shell npm run build --prefix ../src/vue
  become: no
  environment:
    API_URL: "{{ api_url }}"
    SENTRY_DSN: "{{ sentry_dsn }}"
    SENTRY_ORGANIZATION_SLUG: "{{ sentry_organization_slug }}"
    SENTRY_PROJECT_SLUG: "{{ sentry_project_slug }}"
