---

- include: install_additional_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_maintenance_page.yml

- include: create_backup_dir.yml

- include: backup_media.yml
  tags:
    - never
    - deploy_back
    - backup
  when: run_backups

- include: setup_git_repo.yml
  tags: deploy_back

- include: build_frontend.yml
  tags: deploy_front

- include: activate_maintenance_page.yml
  tags:
    - deploy_back
    - deploy_front

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_frontend_file_structure.yml
  tags: deploy_front

- include: setup_django_app.yml
  tags: deploy_back

- include: setup_supervisor.yml
  tags: supervisor

- include: run_django_preset_db.yml
  tags:
    - never
    - run_preset_db
  when: env != 'production'

- include: setup_nginx.yml
