---

- name: Remove {{ frontend_web_dir }} contents
  file:
    state: absent
    path: "{{ frontend_web_dir }}/"

- name: Recreate {{ frontend_web_dir }} directory
  file:
    state: directory
    path: "{{ frontend_web_dir }}/"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755

# TODO Find a better solution for synchronize no tty present errors
- name: (DEBUG) Allow RSYNC for user {{ server_user }} without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^%sudo'
    line: "{{ server_user }} ALL=NOPASSWD: /usr/bin/rsync"

- name: Copy the vuejs files over to {{ frontend_web_dir }}
  synchronize:
    src: ../src/vue/dist/
    dest: "{{ frontend_web_dir }}/"
    recursive: yes

- name: (DEBUG) Disallow RSYNC for user {{ server_user }} without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: absent
    insertafter: '^%sudo'
    line: "{{ server_user }} ALL=NOPASSWD: /usr/bin/rsync"

- name: Ensure that the frontend file permissions are set properly
  file: path={{ frontend_web_dir }}
        recurse=yes
        owner={{ nginx_user }}
        group={{ nginx_group }}
        mode=0755
  changed_when: false
