---

- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=present
  tags: packages
  become: yes

- name: Check if a strong Diffie-Hellman group already exists.
  stat:
    path: "{{ nginx_ssl_dest_dir }}/certs/dhparams.pem"
  register: dhparams

- name: Ensure that a strong Diffie-Hellman group is used
  command: openssl dhparam -out {{ nginx_ssl_dest_dir }}/certs/dhparams.pem 2048 creates={{ nginx_ssl_dest_dir }}/certs/dhparams.pem
  become: yes
  when: not dhparams.stat.exists

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx
  become: yes

- name: Update nginx.conf (base nginx settings)
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  become: yes

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
  become: yes
