# Generated by Django 2.2.8 on 2020-04-12 13:43

from django.db import migrations, models

import VLE.utils.file_handling


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0040_group_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontext',
            name='file',
            field=models.FileField(max_length=255, upload_to=VLE.utils.file_handling.get_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='feedback_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=VLE.utils.file_handling.get_feedback_file_path),
        ),
    ]
