# Generated by Django 2.2.10 on 2020-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0047_dynamic_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(choices=[('t', 'text'), ('rt', 'rich text'), ('f', 'file'), ('v', 'vid'), ('u', 'url'), ('d', 'date'), ('dt', 'datetime'), ('s', 'selection'), ('n', 'no submission')], default='t', max_length=4),
        ),
    ]
