# Generated by Django 2.2.10 on 2020-07-26 12:22

from django.db import migrations, models


def set_permission_for_teachers(apps, schema_editor):
    Role = apps.get_model('VLE', 'Role')
    Role.objects.filter(name='Teacher').update(can_post_teacher_entries=True)

class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0047_dynamic_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_post_teacher_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.TextField(choices=[('t', 'text'), ('rt', 'rich text'), ('f', 'file'), ('v', 'vid'), ('u', 'url'), ('d', 'date'), ('dt', 'datetime'), ('s', 'selection'), ('n', 'no submission')], default='t', max_length=4),
        ),
        migrations.RunPython(
            set_permission_for_teachers,
        ),
    ]
