# Generated by Django 2.2.10 on 2020-08-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0047_dynamic_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_request_source', to='VLE.Journal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_request_target', to='VLE.Journal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
