# Generated by Django 2.2.10 on 2020-08-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0047_dynamic_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PEN', 'Pending'), ('DEC', 'Declined'), ('AIG', 'Approved including grades'), ('AEG', 'Approved excluding grades')], default='PEN', max_length=3)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jir_author', to=settings.AUTH_USER_MODEL)),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jir_processor', to='VLE.Journal')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_request_source', to='VLE.Journal')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_request_target', to='VLE.Journal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
