# Generated by Django 2.2.10 on 2020-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0048_remove_preferences_upcoming_deadline_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='upcoming_deadline_reminder',
            field=models.TextField(choices=[('p', 'a'), ('w', 'w'), ('d', 'd'), ('o', 'o')], default='p', max_length=1),
        ),
    ]
