# Generated by Django 2.2.10 on 2020-08-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLE', '0049_auto_20200726_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VLE.Entry')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLE.Assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('VLE.entry',),
        ),
        migrations.AddField(
            model_name='entry',
            name='teacher_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VLE.TeacherEntry'),
        ),
    ]
