all:
  vars:
    base_domain: ejournal.app
    admin_email: admin@{{ base_domain }}
  children:
    staging:
      vars:
        env: stage
        server_user: mel
      hosts:
        test.ejournal.app:
          ejournal_frontend_domain: test.{{ base_domain }}
          ejournal_backend_domain: api.{{ ejournal_frontend_domain }}
          baselink: https://{{ ejournal_frontend_domain }}
          api_url: https://{{ ejournal_backend_domain }}
          mailgun_sender_domain: "{{ ejournal_frontend_domain }}"
    production:
      vars:
        env: production
        server_user: mel
      hosts:
        uva.ejournal.app:
          ejournal_frontend_domain: uva.{{ base_domain }}
          ejournal_backend_domain: api.{{ ejournal_frontend_domain }}
          baselink: https://{{ ejournal_frontend_domain }}
          api_url: https://{{ ejournal_backend_domain }}
          mailgun_sender_domain: "{{ ejournal_frontend_domain }}"
