---

certbot_script: certbot # Available due to installation via package
certbot_output_dir: "/etc/letsencrypt/live"
letsencrypt_cert_filename: fullchain.pem
letsencrypt_privkey_filename: privkey.pem

# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

# Parameters used when creating new Certbot certs.
certbot_certs: []
# Example certbot_certs structure:
# - email: admin@ejournal.app
#   domain: sentry.ejournal.app
# - domain: grafana.ejournal.app
# - domain: prometheus.ejournal.app
