---

- name: Check if certificate already exists.
  stat:
    path: "{{ certbot_output_dir }}/{{ cert_item.domain }}/cert.pem"
  register: letsencrypt_cert
  become: yes

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_script }} certonly --standalone --noninteractive --agree-tos --email {{ cert_item.email | default(admin_email) }} -d {{ cert_item.domain }}"
  args:
    creates: "{{ certbot_output_dir }}/{{ cert_item.domain }}"
  when: not letsencrypt_cert.stat.exists
  become: yes
