---

- include: install_certbot.yml

- name: Check if Nginx exists
  stat: path=/etc/init.d/nginx
  register: nginx_status

- name: Ensure Nginx is stopped
  service: name=nginx state=stopped
  when: nginx_status.stat.exists
  become: yes

- include_tasks: create_standalone_certificate.yml
  with_items: "{{ certbot_certs }}"
  loop_control:
    loop_var: cert_item

- name: Ensure a cron job to auto-renew the certs exists
  cron:
    name: "Daily cerbot certificate renewal"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    job: "{{ certbot_script }} renew --nginx"
    state: present
  become: yes

- name: Ensure Nginx service is started
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
